server:
  port: 8081

spring:
  redis:
    database: 0
    host: 10.96.2.128
    port: 6379
    password: 123456
    timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  server:
    port: 8998
