apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratelimit-service
  name: ratelimit-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8998"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: ratelimit-service
    spec:
      containers:
        - image: harbor.edu.cn/nju07/ratelimit-service:{VERSION}
          name: ratelimit-service
          ports:
            - name: http
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit-service
  labels:
    app: ratelimit-service
spec:
  type: NodePort
  selector:
    app: ratelimit-service
  ports:
    - name: tcp
      protocol: TCP
      port: 8998
      targetPort: 8998
    - name: http
      protocol: HTTP
      port: 8081
      nodePort: 8081
